CREATE TABLE [dbo].[Workers]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
	[FirstName] NVARCHAR(256) NOT NULL,
	[LastName] NVARCHAR(256) NOT NULL, 
    [DateOfBirth] DATE NOT NULL,
	[City] NVARCHAR(50) NOT NULL,
	[Country] NVARCHAR(50) NOT NULL,
	[HomeAddress] NVARCHAR(256) NOT NULL,
	[CellphoneNumber] VARCHAR(30) NOT NULL,
	[EmailAddress] VARCHAR(100) NOT NULL,
	[WorkerType] NVARCHAR(20) NOT NULL,
	[CreationDate] DATETIME NOT NULL, 
    [UpdatedDate] DATETIME NULL,

    PRIMARY KEY(Id)
)